---
# tasks file for ansible-role-php
- name: Define php_packages
  set_fact:
    php_packages: "{{ php_minimal_packages | list + php_base_packages }}"
  when: php_packages is not defined

- name: Define php_packages with PHP-FPM
  set_fact:
    php_packages: "{{ php_packages | list + php_fpm_package }}"
  when: php_enable_php_fpm == true

- name: Define extra php_packages
  set_fact:
    php_packages: "{{ php_packages | list + php_packages_extra | list }}"
  when: php_packages_extra is defined

- name: Install PHP packages
  apt:
    name: "{{ item }}"
    state: "{{ php_packages_state }}"
    install_recommends: "{{ php_install_recommends }}"
    update_cache: yes
    cache_valid_time: 86400
  with_items: "{{ php_packages }}"
  register: php_package_install
